### ISSUE TITLE
fix(analytics): just track page views

### ISSUE THREAD

**Issue by italosantana** [sibelius/zettelkasten#17]
![image](https://user-images.githubusercontent.com/48260257/204797988-52e2ad20-333c-4683-8ad4-72f706f5ad71.png)

**Comment by italosantana** [comment]
@sibelius did you have tried to change preset option to plugin option gtag?

**Comment by italosantana** [comment]
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag

**Comment by sibelius** [comment]
it is working as expected, what is broken ?

**Comment by italosantana** [comment]
Wrongly opened because I understood it was broken. D:
