### ISSUE TITLE
fix github icon button on header

### ISSUE THREAD

**Issue by sibelius** [sibelius/zettelkasten#5]
![image](https://user-images.githubusercontent.com/2005841/204546794-a75a978b-8a50-4751-95b6-f705089b1fd8.png)

**Comment by ViniBGoulart** [comment]
fix what? Find a better icon?

**Comment by sibelius** [comment]
there is a hidden icon besides the octopus and dark mode

**Comment by ViniBGoulart** [comment]
![image](https://user-images.githubusercontent.com/88122830/204604393-bb1a43bb-511c-49df-bd91-fe8f4797fe14.png)

you have an item there that doesn't show up, can i remove it? or should you stay here
